version: '3.8'

services:
  # Reverse proxy for MCP routing
  proxy:
    image: nginx:alpine
    container_name: mcp-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped

  # Cloudflare tunnel for secure access
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: mcp-tunnel
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared-config.yml:/etc/cloudflared/config.yml:ro
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - proxy

  # MCP Server: filesystem
  mcp-filesystem:
    image: node:20-alpine
    container_name: mcp-filesystem
    working_dir: /app
    command: sh -c "npx @modelcontextprotocol/server-filesystem /workspace"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ${HOME}:/workspace:ro

  # MCP Server: github
  mcp-github:
    image: node:20-alpine
    container_name: mcp-github
    working_dir: /app
    command: sh -c "npx @modelcontextprotocol/server-github"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ${HOME}:/workspace:ro

